spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306
    username: root
    password: '19990102'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      springframework:
        web: INFO
        validation: INFO


mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰和下划线的映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080
